### ISSUE TITLE
OIDC redirect

### ISSUE THREAD

**Issue by jakepm** [worldcoin/minikit-js#119]
Hi, I’m integrating World ID login into my app using a standard OIDC flow (not Next.js or next-auth). In the Next.js example, calling signIn("worldcoin") triggers a native World App UI popup instead of a normal OIDC redirect. Is there a way to trigger that same native popup flow outside of Next.js, using minikit-js or another approach?

@0xPenryn @andy-t-wang

**Comment by andy-t-wang** [comment]
yes any sign in as a miniapp will be handled

**Comment by jakepm** [comment]
Thank you - the mini-app login UI is indeed working even though my back-end initiates the OAuth sequence. Nice!
